# Generated by Django 2.2.4 on 2020-07-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TvShowApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showsnew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('network', models.CharField(max_length=100)),
                ('release_date', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
